### ISSUE TITLE
I'm getting an error

### ISSUE THREAD

**Issue by shodanx2** [ag42dev/bmcd#1]
```
root@debian:/# install -d /opt/bmcd -o 1000 -g 1000 && \
docker run -d \
        --name bmcd \
        --restart unless-stopped \
        -p 27015:27015 \
        -p 27015:27015/udp \
        -v /opt/bmcd:/home/steam/bmcd \
        -e BMCD_HOSTNAME="New Black Mesa Co-op Server" \
        -e BMCD_PW="" \
ghcr.io/ag42dev/bmc
Unable to find image 'ghcr.io/ag42dev/bmc:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/ag42dev/bmc/manifests/latest": denied.
See 'docker run --help'.
root@debian:/# 
```

**Comment by krangm** [comment]
> ```
> root@debian:/# install -d /opt/bmcd -o 1000 -g 1000 && \
> docker run -d \
>         --name bmcd \
>         --restart unless-stopped \
>         -p 27015:27015 \
>         -p 27015:27015/udp \
>         -v /opt/bmcd:/home/steam/bmcd \
>         -e BMCD_HOSTNAME="New Black Mesa Co-op Server" \
>         -e BMCD_PW="" \
> ghcr.io/ag42dev/bmc
> Unable to find image 'ghcr.io/ag42dev/bmc:latest' locally
> docker: Error response from daemon: Head "https://ghcr.io/v2/ag42dev/bmc/manifests/latest": denied.
> See 'docker run --help'.
> root@debian:/# 
> ```

It seems you are missing the very last letter `d` in the image link, it should be `bmcd` not `bmc`
